# Site settings
title: 'Gustavo "Cicloid" Barron — Principal Engineer'
description: "Señor engineer. I build reliable systems and ship pragmatic solutions. Links to projects, writing, and contact."
url: "https://42fu.com"
baseurl: ""

# Author information
author:
  name: "Gustavo Barron"
  email: "hi@42fu.com"
  linkedin: "cicloid"
  github: "cicloid"
  twitter: "cicloid"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - README.md

# GitHub Pages specific settings
github: [metadata]

# SEO and social
twitter:
  username: cicloid
  card: summary_large_image

social:
  name: Gustavo Barron
  links:
    - https://www.linkedin.com/in/cicloid
    - https://github.com/cicloid
    - https://twitter.com/cicloid

